{% set version = "2018.05.22.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-directlabels
  version: {{ version|replace("-", "_") }}

source:
  fn: directlabels_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/directlabels_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/directlabels/directlabels_{{ version }}.tar.gz
  sha256: 016a553f758ac7d83ced8c6e3d8cc338c5110a280c8f7368928b3bdd5362237a

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-quadprog

  run:
    - r-base
    - r-quadprog

test:
  commands:
    - $R -e "library('directlabels')"  # [not win]
    - "\"%R%\" -e \"library('directlabels')\""  # [win]

about:
  home: http://directlabels.r-forge.r-project.org/
  license: GPL-3
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
  summary: An extensible framework for automatically placing direct labels onto multicolor 'lattice'
    or 'ggplot2' plots. Label positions are described using Positioning Methods which
    can be re-used across several different plots. There are heuristics for examining
    "trellis" and "ggplot" objects and inferring an appropriate Positioning Method.

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - nsoranzo
