travis:
  secure:
    BINSTAR_TOKEN: l7uLzz+oAwStQWY5fNaGFfqpRVbP/h8UTjgFJ5SY0k/Dg/JpHlYD+lzLnNREuhu7o1sAJVpem1Ecvh4/58spu4o0xg276Vs8GQRLiAjNw8w5B/I1vXPS/RlzUZ0LD2cCQktziGYFNQnMpWUsuoCRLRNeW2ZJ7pYpZI9459uBXHMh14C8abFxv8h0mjvJL+ZU5mmxGzqxHF9IgA0EsvayewkcZVViCGRVP4lSEfjbQhgxRJaExtU9JWsReQPwBvvOR+4UgQ1tfoxxeXGE4bGaTFiHL4uUtbXMUGK+gCTKDzzV7jHZO7wT58pO8gq4+XlmJXuEGi9xKzh4RWyAOjzER4ZUOfBhqM72ZnL0IhZVahmWZnuzrXbEGQpVtG89ty/ONK6g3HGHupA5SmSR25hQavSmWfcv4E7fzq5hM6B3I/3krc03mZ8LKLmwZSRI1RS4qzWIyDZQaBQWgd8iaTkZy+NqWtwR9XSMjkv3JChWUyiL+WwVMdnh6y79E86Mzdzy80VQtOpqD6bNP1upZ89VzwCiAy2D6QgWQSs8gopg4LCiqxIhr97ZdGqATfe0j5J1u5sA8uVDkk5rS2EprLEpuV+NldcGnUrIA0m2SVjZXOLQY+NcQ3NXOqjui034vQ20BcGWId2A4uAYY7WWvjwP1eFOcL1n9CQogxj+mqkVrDs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
