travis:
  secure:
    BINSTAR_TOKEN: AF5J1t4ILw5eW5V1tFB/yjIvon31G8Z3QRNFFXrfNXiETLVi/mOfX3jH7axzictej5Obd1OQRDeOq+EWAkksdpUEhZ9qGdNbYZrQ8dQfC6sr0a7hdkIhGool5BizhoJ9pbxLE6SctGkqKiqhk2oE+0lSj8IdBM8hpT3+1mNV1xohoq+OU6QmkXue+/A5Lu3dbAAmZsur87/N3Ce4eiLVzhTvkE2Lld0ES1BiwpfHqHCDmZ4AgWHwPmegpNbx0kTljE/5jhU19DrjqWwGqEy2TudiquF5O7p2pns0rWPF8Ymiwb7dG5PaFIenGxmsdcRZHNU2wyJnteF8IqNaZXX3DNGk94cXCM8kIjwoZPVGnXFoJaEo2WeRIe1OMv4sQWDZiNeDX560K+tkeE9Z6eUNhlbLmybka88L8q3nnSeTfcByNijGamI3U1AUNn+H8ikEAZRmARtNwMKHUcSY75kjSF0EBUQf3AKOVHTWTBlzI0LJk/ZqtOYoXnHVz7mISpGC7DaE4ng/IVOZYoJrxoMdaL44ovDu1PLzdCYRmsFGwVr5UNiCrc5rQRl+Y9qbyLjMv+//J193jzeu1XOaeVj+Z/Nj4iU+sS5K1MNDN91KsiaqC1SIIsS9wU9zGSO02ocW/BSxnRv7a45RMN5RYW5PWrN9bc5JteB+o1j78KLtS0g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
