appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hx5nCVgow9B2wR/eeB9MzTCcE6BgqfFWdGXZjgz7hWXDbvJCq6eNcWcZ9dNYkCabmYxtnK35tD0RCR23+mA6vJOD8izm3n79wplT0bpUzPVms3syHJQp5Az0nN1M0YoS2AY9rngzBKdiKgPbz+2VGkYSpf0yDe+KJ8tu6FJEUKApHWmkyLEErI4PtREG+qLD64QRFSHA/Bc0l2oVhlkfLGXJ1DPUvtx8pghILWik6QcqCeUHFePvT+ulSXOHg2brsG2uWC8za2rd6XEmgI7686yO+i8TAPGbfgjd8PBqURusdNfHBkyxa8MbkLVvJHBGtqrtEi4CxvjOtHeYE7G8CiyIIAm0YBl3fu7wvvpm721is6fHGNfBwIiwIU2T3S+4ccfPHNziTWCI0clAKg3e/c1NEwjcsnOUUGz9tvDVDzpmmiIGkg6SQ1dTAWFsVLSgrQjJm1IyvtUxKzmWHASYpEgYrJP9gtl7EFyuh9zr+P5irACjM4udiCABU8NlFE3kcr/Z6TQLA6MuYeYY/TA+V3QSgpBThIwb60H9vfavtQjHALWo/PWjvIeMbBUrGDjtKM7vrz6avGVm8ylLlT2ywaNvxhZqYzChczzY0AaMFiMtHUz/shoNWl10CIspVct5Mm6gi6ySuYZL+hhv+h2zHy8nQj6MVrZPKTFwgTjdTIs=}
